language: python
install:
  - pip install .
script: python -m unittest discover tests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "XIOAfvPQHCeIZH9O4f8ZvG6lMsxaliV/2UwaIUSR78UWJ7QS5Uk4fwxrASTQHJ4Mfd8P6B5ESZND4wCaRPDaaPJUNYNjtii/epVqr1mVkiJv+605iGS73bIyjZA59iihXLVGKNWftG1vH3+t0hDT1pDIVuiyMVLmw+4WMTYNq5XFwFmBd7jJsxV59/m0xhmEiZ1bRITStKNP8ITraAh3hyYLrWP/zqJy3gX8l0FTUboSFjzp0IlypIEsSufZhQSOX1Jdacj4ck78GKgTTiyHqaNEYAOXQZlSPijYshHGWGTeRRm6Jk89TEZj01NwWk4zBszINqxHLklsVnvEaJ06iLPkLvnHpzCcmq3ZJb2QbRLKO0+XPMOnm3huomH2VxPV0u4J9Cn0/9XHCoEnoTlEiya4ANz1a/9A0BAhcCAwSYsNsrCpjsAcgIo9PLkXCJvP2t86i7F0A79oaXrgg4nTZCQXjYnrRmybF770udmHf/5QpyGl6hAXX82w74yz7C43HHr4BpbndLDSc+NjvdFrjpjj1B684ptscsLFNAXZoGGDy55R6aSt6nqwA4/Q8yoF8zoAiRPNDNxBMQKe090A8ZVMm/iZgfElXA4ee0mpynkyxUmGqBDhaGESg90UDlwRMgiqF1A9mmA92KMy1baFDlLHpfb0LmWwnTFJ3Q6Gias="
  on:
    tags: true
